apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: harrytang
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: harrytang-infra
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: it@harrytang.xyz
        name: mrgitops
      signingKey:
        secretRef:
          name: fluxcd-signing-key
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./apps/staging # will be replaced based on environment
    strategy: Setters
