apiVersion: v1
kind: ConfigMap
metadata:
  name: headless-env
data:
  # Strapi
  STRAPI_ADMIN_BACKEND_URL: 'https://headless.harrytang.xyz'
  # Database
  DATABASE_NAME: 'harrytang-prod-headless'
  DATABASE_USERNAME: 'harrytang-prod-headless'
  # STORAGE
  STORAGE_ROOT_PATH: 'prod'
