apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: umami-http
spec:
  parentRefs:
    - name: harrytang
      namespace: gateway
      sectionName: wildcard-http
  hostnames:
    - webb-next.harrytang.xyz # will be replaced based on the environment
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: umami-https
spec:
  parentRefs:
    - name: harrytang
      namespace: gateway
      sectionName: wildcard-https
  hostnames:
    - webb-next.harrytang.xyz # will be replaced based on the environment
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: next.harrytang.xyz # will be replaced based on the environment
            statusCode: 302
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: umami
          namespace: umami
          port: 3000
