apiVersion: v1
kind: ConfigMap
metadata:
  name: headless-env
data:
  # Strapi
  STRAPI_ADMIN_BACKEND_URL: 'https://headless-next.harrytang.xyz'
  # Database
  DATABASE_NAME: 'staging_harry_strapi'
  DATABASE_USERNAME: 'staging_harry_strapi'
  # SMTP
  # STORAGE
  STORAGE_ROOT_PATH: 'next'
