apiVersion: v1
kind: ConfigMap
metadata:
  name: headless-env
data:
  # Strapi
  NODE_ENV: 'production'
  HOST: '0.0.0.0'
  PORT: '1337'
  STRAPI_TELEMETRY_DISABLED: 'true'
  # Database
  DATABASE_CLIENT: 'mysql'
  DATABASE_HOST: 'maxscale-galera.galera'
  DATABASE_PORT: '3306'
  DATABASE_SSL: 'false'
  # SMTP
  SMTP_HOST: 'smtp.tem.scw.cloud'
  SMTP_PORT: '587'
  SMTP_USERNAME: '3da79532-3cf3-4f03-b74c-82f3ee4952d3'
  SMTP_FROM: 'no-reply@notify.harrytang.xyz'
  # STORAGE
  STORAGE_HOST: 'assets.harrytang.xyz'
  CF_ACCESS_KEY_ID: 'af6ed96bab6432014daf36f67b608203'
  CF_ENDPOINT: 'https://4389df0f0fbc35755e761a69eaebf297.r2.cloudflarestorage.com'
  CF_BUCKET: 'harrytang'
