apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/headless
  - ./headless/sealed-secret.yaml
patches:
  - path: ./headless/config-map.yaml
    target:
      kind: ConfigMap
      name: headless-env
  - path: ./headless/depl.yaml
    target:
      kind: Deployment
      name: headless
