apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/headless
patches:
  - path: ./headless/config-map.yaml
    target:
      kind: ConfigMap
      name: headless-env