apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/headless
  - ../base/umami
  - ./headless/sealed-secret.yaml
patches:
  - path: ./headless/config-map.yaml
    target:
      kind: ConfigMap
      name: headless-env
  - path: ./headless/depl.yaml
    target:
      kind: Deployment
      name: headless
  - path: ./headless/http-route.yaml
    target:
      kind: HTTPRoute
      name: headless-http
  - path: ./headless/https-route.yaml
    target:
      kind: HTTPRoute
      name: headless-https
  # Umami
  - path: ./umami/http-route.yaml
    target:
      kind: HTTPRoute
      name: umami-http
  - path: ./umami/https-route.yaml
    target:
      kind: HTTPRoute
      name: umami-https