apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/headless
  - ../base/umami
  - ../base/remark42
  - ../base/web
  - ./web/sealed-secret.yaml
  - ./headless/sealed-secret.yaml
  - ./remark42/sealed-secret.yaml
patches:
  - path: ./headless/config-map.yaml
    target:
      kind: ConfigMap
      name: headless-env
  - path: ./headless/depl.yaml
    target:
      kind: Deployment
      name: headless
  - path: ./headless/http-route.yaml
    target:
      kind: HTTPRoute
      name: headless-http
  - path: ./headless/https-route.yaml
    target:
      kind: HTTPRoute
      name: headless-https
  # Umami
  - path: ./umami/http-route.yaml
    target:
      kind: HTTPRoute
      name: umami-http
  - path: ./umami/https-route.yaml
    target:
      kind: HTTPRoute
      name: umami-https
  # Remark42
  - path: ./remark42/http-route.yaml
    target:
      kind: HTTPRoute
      name: remark42-http
  - path: ./remark42/https-route.yaml
    target:
      kind: HTTPRoute
      name: remark42-https
  - path: ./remark42/depl.yaml
    target:
      kind: Deployment
      name: remark42
  - path: ./remark42/config-map.yaml
    target:
      kind: ConfigMap
      name: remark42
  # Web
  - path: ./web/http-route.yaml
    target:
      kind: HTTPRoute
      name: web-http
  - path: ./web/https-route.yaml
    target:
      kind: HTTPRoute
      name: web-https
  - path: ./web/depl.yaml
    target:
      kind: Deployment
      name: web
  - path: ./web/config-map.yaml
    target:
      kind: ConfigMap
      name: web-env