apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: remark42-http
spec:
  parentRefs:
    - name: harrytang
      namespace: gateway
      sectionName: wildcard-http
  hostnames:
    - comment-next.harrytang.xyz # will be replaced based on the environment
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: remark42-https
spec:
  parentRefs:
    - name: harrytang
      namespace: gateway
      sectionName: wildcard-https
  hostnames:
    - comment-next.harrytang.xyz # will be replaced based on the environment
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: remark42
          port: 8080
