---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-www-http
spec:
  parentRefs:
    - name: harrytang
      namespace: gateway
      sectionName: wildcard-http
  hostnames:
    - www.harrytang.xyz
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: harrytang.xyz
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-www-https
spec:
  parentRefs:
    - name: harrytang
      namespace: gateway
      sectionName: wildcard-https
  hostnames:
    - www.harrytang.xyz
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: harrytang.xyz
            statusCode: 301
